# Generated by Django 5.2.8 on 2025-11-17 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vacancy_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='city',
            new_name='location',
        ),
    ]
