# Generated by Django 5.2.8 on 2025-11-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='skills',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_experience',
            field=models.CharField(blank=True, choices=[('no_exp', 'No experience'), ('1_3', 'From 1 to 3 years'), ('3_6', 'From 3 to 6 years'), ('6_plus', 'More than 6 years')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment',
            field=models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('internship', 'Internship'), ('part_time', 'Part-time'), ('contract', 'Contract work'), ('fifo', 'FIFO'), ('volunteer', 'Volunteering')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='level_of_education',
            field=models.CharField(blank=True, choices=[('bachelor', "Bachelor's degree"), ('master', "Master's degree"), ('phd', 'PhD'), ('doctor', 'Doctor of Sciences'), ('higher', 'Higher education'), ('incomplete_higher', 'Incomplete higher education'), ('secondary', 'Secondary education'), ('vocational', 'Vocational education')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_format',
            field=models.CharField(blank=True, choices=[('hybrid', 'Hybrid'), ('split', 'Split'), ('on_site', 'On-site'), ('remote', 'Remote')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='schedule',
            field=models.CharField(blank=True, null=True),
        ),
    ]
